### ISSUE TITLE
removeMarkers doesn't remove all markers

### ISSUE THREAD

**Issue by fatshotty** [gmaps-marker-clusterer/gmaps-marker-clusterer#25]
Hi,
I try to remove all markers in MarkerClusterer, but it doesn't remove all of them.

I think problem could be around this line of code

https://github.com/googlemaps/js-marker-clusterer/blob/gh-pages/src/markerclusterer.js#L510

It loops in markers array incrementing the i index, but in `removeMarker_` function it performs a `splice` that changes the length of the array and, then, its indexes.
That causes not all markers will be removed.

Is it only me?

I tried this code:
```js
.....
var markerCluster = new MarkerClusterer(myMap, markers);
.....
markerCluster.removeMarkers( markerCluster.getMarkers() );
```

Thanks in advance

**Comment by Remo** [comment]
Thanks, will have a look at this!
Original report: https://github.com/googlemaps/js-marker-clusterer/issues/119#event-1018232209

**Comment by Remo** [comment]
I think the problem happens because we are working with references, if you clone the whole thing, it works:

```javascript
var markers = Object.assign({}, markerCluster.getMarkers());
markerCluster.removeMarkers(markers);
```

We might be able to fix this be looping through the markers in reverse. Can you check if this works for you: https://github.com/gmaps-marker-clusterer/gmaps-marker-clusterer/pull/26 ?

**Comment by fatshotty** [comment]
yes, it works :)

**Comment by Remo** [comment]
I think doing this in reverse is fine. The problem isn't related to the index, but rather to the fact that we are having references pointing to the original array. Assuming we have 5 markers and want to remove them we call `removeMarkers` with an array with 5 items. Within that method we start with 5 items, but after the loop has processes its first item we'll only have 4 items left since `removeMarker_` removes the item from the internal markers array and because we just have a reference to it, our function fails.
