### ISSUE TITLE
Update the Documenation

### ISSUE THREAD

**Issue by XmlmXmlmX** [gmaps-marker-clusterer/gmaps-marker-clusterer#4]
The documentation needs a update.

- All links are referenced to the old documentation.
- The layout and design is very outdated.

Maybe a additional branch for a GitHub Page would be useful, to host the documentation and the examples #5?

**Comment by Remo** [comment]
Shall we start with a wiki or a jekyll page in gh-pages? Wiki would be easy to start, but we can't add any examples. Maybe something like this http://mistic100.github.io/jekyll-bootstrap-doc/?

**Comment by XmlmXmlmX** [comment]
I prefer the jekyll variant.

**Comment by Remo** [comment]
Any good theme you know of? I'd prefer something simple on one page with a TOC and just some links for examples. Did some research, but my favourite is still the one above. If someone feels bored it would also be easy to change due to its simplicity.

* http://mistic100.github.io/jekyll-bootstrap-doc/
* https://tangerine-lemon.cloudvent.net/
* http://wiredcraft.github.io/carte/
* http://www.tuicode.com/article/5747d65b6f6491c54812c20f
* http://dbtek.github.io/dbyll/
* http://idratherbewriting.com/documentation-theme-jekyll/
* http://bruth.github.io/jekyll-docs-template/
* http://digitalmind.ch/themes/docster-jekyll-theme/demo/

**Comment by XmlmXmlmX** [comment]
I like the design of http://mistic100.github.io/jekyll-bootstrap-doc/

**Comment by Remo** [comment]
I've set up the basic structure and copied some content. It's not something I want to show the world, just the foundation.
https://gmaps-marker-clusterer.github.io/gmaps-marker-clusterer/

**Comment by XmlmXmlmX** [comment]
Look awesome @Remo

**Comment by Remo** [comment]
Thanks! Just some examples missing and then we already have what google had. I left the links in the README till we have the advanced examples in our documentation.

**Comment by Remo** [comment]
It's not perfect, but I think it's already better than the old documentation. Going to close this.
